"""migration

Revision ID: 7327c4d606d9
Revises: 7a029e20fc40
Create Date: 2025-04-04 19:54:12.051796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7327c4d606d9'
down_revision: Union[str, None] = '7a029e20fc40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('centros_treinamento_proprietario_key', 'centros_treinamento', type_='unique')
    op.create_unique_constraint(None, 'centros_treinamento', ['nome'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'centros_treinamento', type_='unique')
    op.create_unique_constraint('centros_treinamento_proprietario_key', 'centros_treinamento', ['proprietario'])
    # ### end Alembic commands ###
